#!/usr/bin/python

words = ['JAZZ','HELLO','WORLD','PYTHON','BUZZ',
         'QUIZ','BUZZING','PARALLAXES','BEEKEEPERS','DIZZY',
         'FUZZIEST','SHABBINESS','MUMMIFYING','COZY','FOXED',
         'JINXING','JAYWALKING','GROGGINESS','FLUFFINESS','FULFILLING']
